using System;
using System.Collections.Generic;
using BusinessModelApp.Core.Domain.Missions;
using BusinessModelApp.Core.Domain.Responsibilities;
using BusinessModelApp.Core.Domain.Runtime.Capabilities;
using BusinessModelApp.Core.Domain.Runtime.Reputation;
using BusinessModelApp.Core.Domain.Runtime.Workers;

namespace BusinessModelApp.Core.Domain.Runtime.Capabilities.Factory
{
    /// <summary>
    /// Explicit 18-State Lifecycle for Autonomous Capabilities.
    /// Invariant I17 / I17-A: Every generated capability begins as UNTRUSTED DRAFT.
    /// </summary>
    public enum CapabilityLifecycleState
    {
        Draft = 0,
        Specified = 1,
        Designed = 2,
        Generated = 3,
        StaticScanned = 4,
        Sandboxed = 5,
        TddPassed = 6,
        Evaluated = 7,
        RedTeamed = 8,
        RegressionVerified = 9,
        Certified = 10,
        Signed = 11,
        Registered = 12,
        Shadow = 13,
        Probation = 14,
        Active = 15,
        Quarantined = 16,
        Revoked = 17,

        // Terminal & Control States
        Rejected = 18,
        Deprecated = 19,
        Retired = 20
    }

    /// <summary>
    /// Triggered when an ambient responsibility, mission DAG, or worker resolution
    /// detects an unmet business requirement or missing worker modality.
    /// </summary>
    public record CapabilityGap
    {
        public Guid GapId { get; init; } = Guid.NewGuid();
        public Guid WorkspaceId { get; init; }
        public string TenantId { get; init; } = "default-tenant";
        public MissionId? TriggeringMissionId { get; init; }
        public MissionNodeId? TriggeringNodeId { get; init; }
        public string BusinessNeed { get; init; } = string.Empty;
        public string RequiredCapabilityName { get; init; } = string.Empty;
        public CapabilityRiskTier RiskTierCeiling { get; init; } = CapabilityRiskTier.R1_LowAnalytical;
        public AutonomyTier AutonomyCeiling { get; init; } = AutonomyTier.L3_Prepare;
        public List<WorkerModality> RequiredModalities { get; init; } = new();
        public string ExpectedInputDescription { get; init; } = string.Empty;
        public string ExpectedOutputDescription { get; init; } = string.Empty;
        public DateTimeOffset DetectedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Immutable deterministic specification synthesized prior to any code generation.
    /// Invariant I17-H: Generated capability can never alter this specification.
    /// </summary>
    public record CapabilitySpecification
    {
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public Guid WorkspaceId { get; init; }
        public string TenantId { get; init; } = "default-tenant";
        public Guid GapId { get; init; }
        public string Title { get; init; } = string.Empty;
        public string Description { get; init; } = string.Empty;
        public string BusinessNeed { get; init; } = string.Empty;

        // Schemas
        public string InputSchemaJson { get; init; } = "{}";
        public string OutputSchemaJson { get; init; } = "{}";

        // Preconditions & Invariants
        public List<string> Preconditions { get; init; } = new();
        public List<string> Invariants { get; init; } = new();
        public string VerificationCriteria { get; init; } = string.Empty;

        // Governance Envelopes
        public CapabilityRiskTier RiskCeiling { get; init; } = CapabilityRiskTier.R1_LowAnalytical;
        public AutonomyTier AutonomyCeiling { get; init; } = AutonomyTier.L3_Prepare;
        public bool IsConsequential { get; init; }
        public List<WorkerModality> PermittedModalities { get; init; } = new();

        // Operational Limits
        public TimeSpan DefaultTimeout { get; init; } = TimeSpan.FromMinutes(2);
        public int MaxRetries { get; init; } = 2;
        public double MaxBudgetINR { get; init; } = 10_000.0;
        public int MaxConcurrency { get; init; } = 5;

        // Resource Ceilings for Sandbox
        public int MaxMemoryMB { get; init; } = 512;
        public double MaxCPUCores { get; init; } = 1.0;
        public bool NetworkRestricted { get; init; } = true;
        public bool FilesystemRestricted { get; init; } = true;

        public DateTimeOffset SpecifiedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Architectural design blueprint and threat model generated by AI Designer.
    /// </summary>
    public record CapabilityDesignArtifact
    {
        public Guid DesignId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public string ArchitectureSummary { get; init; } = string.Empty;
        public string ExecutionStrategy { get; init; } = string.Empty;
        public List<string> ApprovedDependencies { get; init; } = new();
        public List<string> ThreatModelRisks { get; init; } = new();
        public List<string> Mitigations { get; init; } = new();
        public string TestPlan { get; init; } = string.Empty;
        public DateTimeOffset DesignedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Generated executable code artifact.
    /// Invariant I17-A: Trust = ZERO, Authority = ZERO, ProductionAccess = ZERO.
    /// </summary>
    public record CapabilityCodeArtifact
    {
        public Guid ArtifactId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public string SourceCode { get; init; } = string.Empty;
        public string RuntimeLanguage { get; init; } = "CSharp"; // CSharp, Python, JavaScript, Template
        public string Entrypoint { get; init; } = "ExecuteAsync";
        public string ManifestJson { get; init; } = "{}";
        public List<string> Dependencies { get; init; } = new();

        // Cryptographic Hashes (SHA-256)
        public string SourceHash { get; init; } = string.Empty;
        public string ManifestHash { get; init; } = string.Empty;
        public string DependencyHash { get; init; } = string.Empty;

        public string GeneratorProvenance { get; init; } = "AutonomousCapabilityFactory/AI";
        public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Multi-layer static security analysis result.
    /// </summary>
    public record StaticSecurityScanResult
    {
        public Guid ScanId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public bool IsPassed { get; init; }
        public int VulnerabilityCount { get; init; }
        public List<string> Violations { get; init; } = new();
        public bool HasProcessSpawnViolation { get; init; }
        public bool HasReflectionViolation { get; init; }
        public bool HasFilesystemEscapeViolation { get; init; }
        public bool HasNetworkEscapeViolation { get; init; }
        public bool HasFirewallBypassViolation { get; init; }
        public bool HasSecretHarvestingViolation { get; init; }
        public bool HasDependencyViolation { get; init; }
        public DateTimeOffset ScannedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Disposable isolated sandbox execution result.
    /// Invariant I17-E: Enforces process, memory, network deny-by-default, and DB isolation.
    /// </summary>
    public record SandboxExecutionResult
    {
        public Guid ExecutionId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public bool IsSuccess { get; init; }
        public int ExitCode { get; init; }
        public TimeSpan Duration { get; init; }
        public long MemoryPeakBytes { get; init; }
        public double CpuUsedPercent { get; init; }
        public long OutputSizeBytes { get; init; }
        public int NetworkDenialCount { get; init; }
        public int FilesystemViolationCount { get; init; }
        public List<string> SecurityViolations { get; init; } = new();
        public string StdOut { get; init; } = string.Empty;
        public string StdErr { get; init; } = string.Empty;
        public DateTimeOffset ExecutedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Deterministic test suite derived from immutable specification.
    /// </summary>
    public record CapabilityTestSuite
    {
        public Guid SuiteId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public string TestSuiteHash { get; init; } = string.Empty; // SHA-256 of immutable tests
        public List<CapabilityTestCase> TestCases { get; init; } = new();
        public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    public record CapabilityTestCase
    {
        public string TestId { get; init; } = Guid.NewGuid().ToString("N");
        public string Name { get; init; } = string.Empty;
        public string InputJson { get; init; } = "{}";
        public string ExpectedOutputPattern { get; init; } = string.Empty;
        public bool IsEdgeCase { get; init; }
        public bool IsSecurityBoundary { get; init; }
    }

    public record TddEvaluationResult
    {
        public Guid EvaluationId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public string TestSuiteHash { get; init; } = string.Empty;
        public int TotalTests { get; init; }
        public int PassedTests { get; init; }
        public int FailedTests { get; init; }
        public double PassRate { get; init; }
        public bool AllInvariantsSatisfied { get; init; }
        public List<string> Failures { get; init; } = new();
        public DateTimeOffset EvaluatedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Strix Adversarial Red-Team Probe Attack Results.
    /// Invariant I17-H: Any breach immediately produces QUARANTINED.
    /// </summary>
    public record StrixRedTeamResult
    {
        public Guid ProbeRunId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public bool IsPassed { get; init; }
        public int AttacksAttempted { get; init; }
        public int AttacksBlocked { get; init; }
        public List<string> Breaches { get; init; } = new();
        public bool PromptInjectionResistant { get; init; }
        public bool OverflowResistant { get; init; }
        public bool PrivilegeEscalationResistant { get; init; }
        public bool FirewallBypassResistant { get; init; }
        public bool RegistryTamperResistant { get; init; }
        public bool SelfPromotionResistant { get; init; }
        public DateTimeOffset ProbedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Comprehensive Empirical Multi-Dimensional Evaluation.
    /// </summary>
    public record CapabilityEvaluationScorecard
    {
        public Guid ScorecardId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public double CorrectnessScore { get; init; } // 0.0 - 1.0
        public double SchemaConformanceScore { get; init; }
        public double LatencySlaScore { get; init; }
        public double ResourceEfficiencyScore { get; init; }
        public double SecurityResilienceScore { get; init; }
        public double DeterminismScore { get; init; }
        public bool IsAdmissibleForCertification { get; init; }
        public string Rationale { get; init; } = string.Empty;
        public DateTimeOffset ScoredAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Independent Certification Authority (ICA) Certificate.
    /// Invariant I17-B: Certifier must be cryptographically and contextually distinct from generator.
    /// </summary>
    public record CapabilityCertificate
    {
        public Guid CertificateId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public string CertifierIdentity { get; init; } = "Sovereign-ICA-Authority";
        public string ArtifactHash { get; init; } = string.Empty;
        public string ManifestHash { get; init; } = string.Empty;
        public string TestSuiteHash { get; init; } = string.Empty;
        public string DependencyHash { get; init; } = string.Empty;
        public string EvidenceBundleHash { get; init; } = string.Empty;
        public CapabilityRiskTier CertifiedRiskCeiling { get; init; }
        public AutonomyTier CertifiedAutonomyCeiling { get; init; }
        public List<string> CertifiedModalities { get; init; } = new();
        public List<string> EnforcedConstraints { get; init; } = new();
        public DateTimeOffset CertifiedAt { get; init; } = DateTimeOffset.UtcNow;
        public DateTimeOffset ValidUntil { get; init; } = DateTimeOffset.UtcNow.AddDays(90);
        public bool IsRevoked { get; set; }
        public string? RevocationReason { get; set; }
    }

    /// <summary>
    /// Governed Cryptographic Release Signature.
    /// Invariant I17-C: Asymmetric digital signature (Ed25519) guaranteeing supply-chain authenticity.
    /// </summary>
    public record CapabilityReleaseSignature
    {
        public Guid SignatureId { get; init; } = Guid.NewGuid();
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public Guid CertificateId { get; init; }
        public string PublicKeyHex { get; init; } = string.Empty;
        public string Algorithm { get; init; } = "Ed25519";
        public string SignatureHex { get; init; } = string.Empty;
        public string SignedManifestPayload { get; init; } = string.Empty;
        public string ParentVersionHash { get; init; } = "ROOT_GENESIS";
        public DateTimeOffset SignedAt { get; init; } = DateTimeOffset.UtcNow;
    }

    /// <summary>
    /// Sealed record inside the Immutable Capability Registry.
    /// </summary>
    public record RegisteredCapabilityRecord
    {
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public Guid WorkspaceId { get; init; }
        public string TenantId { get; init; } = "default-tenant";
        public string Title { get; init; } = string.Empty;
        public string Description { get; init; } = string.Empty;
        public CapabilityLifecycleState State { get; set; } = CapabilityLifecycleState.Registered;
        public CapabilitySpecification Specification { get; init; } = null!;
        public CapabilityCodeArtifact Artifact { get; init; } = null!;
        public CapabilityCertificate Certificate { get; init; } = null!;
        public CapabilityReleaseSignature Signature { get; init; } = null!;
        public List<WorkerModality> PermittedModalities { get; init; } = new();
        public CapabilityRiskTier RiskCeiling { get; init; }
        public AutonomyTier AutonomyCeiling { get; init; }
        public DateTimeOffset RegisteredAt { get; init; } = DateTimeOffset.UtcNow;
        public DateTimeOffset? PromotedToShadowAt { get; set; }
        public DateTimeOffset? PromotedToProbationAt { get; set; }
        public DateTimeOffset? PromotedToActiveAt { get; set; }
        public DateTimeOffset? QuarantinedAt { get; set; }
        public string? QuarantineReason { get; set; }
        public DateTimeOffset? RevokedAt { get; set; }
        public string? RevocationReason { get; set; }
    }

    /// <summary>
    /// Probationary telemetry envelope and bounded error budget tracker.
    /// </summary>
    public class ProbationTracker
    {
        public CapabilityId CapabilityId { get; init; }
        public string Version { get; init; } = "1.0.0";
        public int MaxPermittedExecutions { get; init; } = 100;
        public double MaxPermittedBudgetINR { get; init; } = 5_000.0;
        public double MaxAllowedErrorRate { get; init; } = 0.02; // 2%
        public TimeSpan MaxAllowedLatencySla { get; init; } = TimeSpan.FromSeconds(5);

        public int CurrentExecutionCount { get; set; }
        public int CurrentFailureCount { get; set; }
        public double CurrentSpentINR { get; set; }
        public List<double> RecentLatencyMs { get; } = new();

        public double CurrentErrorRate => CurrentExecutionCount == 0 ? 0.0 : (double)CurrentFailureCount / CurrentExecutionCount;
        public bool IsBreached => CurrentExecutionCount >= MaxPermittedExecutions && CurrentErrorRate > MaxAllowedErrorRate
            || CurrentSpentINR > MaxPermittedBudgetINR
            || CurrentFailureCount >= 3;
    }

    /// <summary>
    /// Evidence bundle containing all proofs required by Independent Certifier.
    /// </summary>
    public record CapabilityEvidenceBundle
    {
        public Guid BundleId { get; init; } = Guid.NewGuid();
        public CapabilitySpecification Specification { get; init; } = null!;
        public CapabilityCodeArtifact Artifact { get; init; } = null!;
        public StaticSecurityScanResult SecurityResult { get; init; } = null!;
        public SandboxExecutionResult SandboxResult { get; init; } = null!;
        public TddEvaluationResult TddResult { get; init; } = null!;
        public StrixRedTeamResult RedTeamResult { get; init; } = null!;
        public CapabilityEvaluationScorecard Scorecard { get; init; } = null!;
        public bool BaselineRegressionPassed { get; init; }
        public int RegressionBaselineCount { get; init; } = 897;
    }
}
