using System;
using System.Collections.Generic;
using BusinessModelApp.Core.Domain.Objectives;
using BusinessModelApp.Core.Domain.Strategy;
using BusinessModelApp.Core.Domain.WorldModel;
using BusinessModelApp.Core.Strategy;
using Microsoft.Extensions.Logging;

namespace BusinessModelApp.Infrastructure.Strategy
{
    public class AIStrategySimulator : IAIStrategySimulator
    {
        private readonly IReverseFunnelEngine _reverseFunnelEngine;
        private readonly ILogger<AIStrategySimulator> _logger;

        public AIStrategySimulator(
            IReverseFunnelEngine reverseFunnelEngine,
            ILogger<AIStrategySimulator> logger)
        {
            _reverseFunnelEngine = reverseFunnelEngine ?? throw new ArgumentNullException(nameof(reverseFunnelEngine));
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        }

        public StrategyCandidate FormulateAIHypothesisRoute(
            string hypothesisName,
            string targetICP,
            string strategicConcept,
            BusinessObjective objective,
            CompanySnapshot snapshot,
            decimal estimatedACVINR,
            double estimatedWinRate,
            int capacitySlotsRequired,
            decimal requiredBudgetINR)
        {
            _logger.LogInformation("[AIStrategySimulator] Formulating AI Hypothesis Route '{HypothesisName}' for ICP '{TargetICP}'",
                hypothesisName, targetICP);

            // AI estimates strictly encapsulated in TruthMetric<T>.Estimated
            var acvMetric = TruthMetric<decimal>.Estimated(estimatedACVINR, $"AI synthesized market estimate for {targetICP}", 0.45);
            var winRateMetric = TruthMetric<double>.Estimated(estimatedWinRate, $"AI heuristic win rate benchmark for {targetICP}", 0.40);

            var funnel = _reverseFunnelEngine.CalculateFunnel(objective.TargetRevenueINR, acvMetric, winRateMetric, snapshot);

            var candidate = new StrategyCandidate
            {
                StrategyId = Guid.NewGuid(),
                Name = hypothesisName,
                ObjectiveTitle = objective.Title,
                ObjectiveId = objective.Id,
                ExpectedRevenueINR = objective.TargetRevenueINR,
                RequiredDeliveryCapacitySlots = capacitySlotsRequired,
                RequiredBudgetINR = requiredBudgetINR,
                TimelineDays = 60,
                RequiredFunnel = funnel,
                IsDeterministic = false
            };

            // Invariant: All assumptions generated by AI simulator are AI_ESTIMATE
            candidate.Assumptions.Add(new AssumptionProvenance
            {
                Key = "HypothesisConcept",
                Description = strategicConcept,
                AssumedValue = targetICP,
                Origin = MetricProvenanceSource.AiEstimate,
                Confidence = 0.50
            });

            candidate.Assumptions.Add(new AssumptionProvenance
            {
                Key = "TargetACV",
                Description = $"Estimated deal size for {targetICP}",
                AssumedValue = $"₹{estimatedACVINR:N0}",
                Origin = MetricProvenanceSource.AiEstimate,
                Confidence = 0.45
            });

            candidate.Assumptions.Add(new AssumptionProvenance
            {
                Key = "WinRate",
                Description = $"Estimated competitive win rate for {targetICP}",
                AssumedValue = $"{estimatedWinRate * 100:N0}%",
                Origin = MetricProvenanceSource.AiEstimate,
                Confidence = 0.40
            });

            candidate.Assumptions.Add(new AssumptionProvenance
            {
                Key = "DeliveryCapacity",
                Description = $"Estimated capacity slots: {capacitySlotsRequired}",
                AssumedValue = $"{capacitySlotsRequired} slots",
                Origin = MetricProvenanceSource.AiEstimate,
                Confidence = 0.70
            });

            var report = new FeasibilityReport
            {
                StrategyId = candidate.StrategyId,
                StrategyName = hypothesisName
            };

            int availableSlots = snapshot.Delivery.AvailableDeliverySlots.Value > 0
                ? snapshot.Delivery.AvailableDeliverySlots.Value
                : snapshot.AvailableDeliverySlots.Value;

            if (capacitySlotsRequired > availableSlots)
            {
                report.Classification = StrategyFeasibilityClassification.UnfeasibleResourceConstrained;
                report.Reasons.Add($"AI route requires {capacitySlotsRequired} delivery slots, exceeding available {availableSlots}.");
                report.ResourceConstraintsViolated.Add($"Delivery Slots: Required {capacitySlotsRequired}, Available {availableSlots}");
            }
            else
            {
                // CRITICAL RULE: Charlie cannot convert an AI estimate into company reality.
                // It remains HYPOTHETICAL_UNVERIFIED until backed by real customer/market validation.
                report.Classification = StrategyFeasibilityClassification.HypotheticalUnverified;
                report.Reasons.Add("Strategy relies on AI-estimated conversion metrics and ungrounded market hypotheses.");
                report.MissingEvidenceItems.Add($"Real-world validation or pipeline evidence from {targetICP} accounts.");
            }

            candidate.Feasibility = report.Classification;
            candidate.FeasibilityReport = report;
            candidate.ConfidenceScore = 0.50; // AI estimates capped at moderate confidence
            candidate.RiskScore = 0.65;       // Unverified hypotheses carry higher risk

            return candidate;
        }
    }
}
